import type { Metadata } from "next";
import "../globals.css";
import NevBar from "../components/NevBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-gray-800">
        <NevBar/>
        {children}
      </body>
    </html>
  );
}
